## 创建数组

In [1]:
import numpy as np
arr1d = np.array([1, 2, 3]) # 创建一维数组
arr1d

array([1, 2, 3])

In [2]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])  # 创建二维数组
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
# 创建三维数组
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])      
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [4]:
np.zeros((3, 3))   # 创建元素值都为0的数组，并指定数组的形状是(3, 3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((3, 3))    # 创建元素值都为1数组，并指定数组的形状是(3, 3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.empty((3, 3))  # 创建未初始化的数组，并指定数组的形状是(3, 3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.arange(1, 20, 5)  # 创建数组，起始值是1，终止值是20，步长为5

array([ 1,  6, 11, 16])

In [8]:
np.linspace(1, 20, 5)  # 创建数组，起始值是1，终止值是20，数量为5

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [9]:
# 创建一个一维数组，指定数据类型为单精度浮点数
np.array([1, 2, 3], dtype=np.float32)

array([1., 2., 3.], dtype=float32)

In [10]:
# 创建元素值都为1的数组，指定数据类型为整数
np.ones((3, 3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

## 【任务2-1】	创建象棋和围棋棋盘

In [11]:
import numpy as np

# 创建一个二维数组，表示象棋棋盘
chessboard = np.array([[0, 1, 0, 1, 0, 1, 0, 1],
                       [1, 0, 1, 0, 1, 0, 1, 0],
                       [0, 1, 0, 1, 0, 1, 0, 1],
                       [1, 0, 1, 0, 1, 0, 1, 0],
                       [0, 1, 0, 1, 0, 1, 0, 1],
                       [1, 0, 1, 0, 1, 0, 1, 0],
                       [0, 1, 0, 1, 0, 1, 0, 1],
                       [1, 0, 1, 0, 1, 0, 1, 0]])
print(chessboard)



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [12]:
import numpy as np

# 创建一个二维数组，表示围棋棋盘
go_board = np.array([[0, 1, 0, 1, 0, 1, 0, 1, 0],
                     [1, 0, 1, 0, 1, 0, 1, 0, 1],
                     [0, 1, 0, 1, 0, 1, 0, 1, 0],
                     [1, 0, 1, 0, 1, 0, 1, 0, 1],
                     [0, 1, 0, 1, 0, 1, 0, 1, 0],
                     [1, 0, 1, 0, 1, 0, 1, 0, 1],
                     [0, 1, 0, 1, 0, 1, 0, 1, 0],
                     [1, 0, 1, 0, 1, 0, 1, 0 ,1],
                     [0 ,1 ,0 ,1 ,0 ,1 ,0 ,1 ,0]])
print(go_board)



[[0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]]


## 整数索引和切片

In [13]:
import numpy as np
arr2d = np.array([[1, 6, 11, 16, 21], [2, 7, 12, 17, 22], 
                      [3, 8, 13, 18, 23], [4, 9, 14, 19, 24], 
                      [5, 10, 15, 20, 25]])
arr2d

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

In [14]:
arr2d[2]           # 获取行索引为2的整行元素

array([ 3,  8, 13, 18, 23])

In [15]:
arr2d[2, 1]        # 获取行索引为2、列索引为1的元素

np.int64(8)

In [16]:
arr2d[:2]           # 获取索引为0、1的两行元素

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22]])

In [17]:
arr2d[:2, :2]      # 获取行索引为0~1，列索引为0~1的部分元素

array([[1, 6],
       [2, 7]])

In [18]:
arr2d[:, 2]         # 获取列索引为2的整列元素

array([11, 12, 13, 14, 15])

## 花式索引

In [19]:
import numpy as np
arr = np.array([10, 6, 5, 11, 18, 16, 9, 0, 3, 20])
arr[[0, 1, 5]]

array([10,  6, 16])

In [20]:
arr2d[[1, 4]]

array([[ 2,  7, 12, 17, 22],
       [ 5, 10, 15, 20, 25]])

In [21]:
arr2d[[1,4], [2, 3]]

array([12, 20])

## 转换数组的数据类型

In [22]:
import numpy as np
data = np.array([[1, 2, 3], [4, 5, 6]])
data.dtype.name

'int64'

In [23]:
float_data = data.astype(np.float32) # 转换数据类型为float32
float_data.dtype.name

'float32'

In [24]:
float_data = np.array([1.2, 2.9, 3.5])
float_data

array([1.2, 2.9, 3.5])

In [25]:
int_data = float_data.astype(np.int32) # 转换数据类型为int32
int_data

array([1, 2, 3], dtype=int32)

In [26]:
str_data = np.array(['1', '2', '3'])
int_data = str_data.astype(np.int64)
int_data

array([1, 2, 3])

## 【任务2-2】 填色小游戏

In [27]:
import numpy as np

# 创建一个8行8列的二维数组，数组的元素都设置为'白'
chessboard = np.full((8, 8), '白')

# 奇数行偶数列的元素设置为’黑’
chessboard[1::2, ::2] = '黑'

# 偶数行奇数列的元素设置为’黑’
chessboard[::2, 1::2] = '黑'

# 四个角的元素设置为'红'
chessboard[0, 0] = '红'
chessboard[0, 7] = '红'
chessboard[7, 0] = '红'
chessboard[7, 7] = '红'


## 布尔索引

In [28]:
import numpy as np
student_score = np.array([[79, 88, 80], [89, 90, 92], 
                               [83, 78, 85], [78, 76, 80]])
student_score

array([[79, 88, 80],
       [89, 90, 92],
       [83, 78, 85],
       [78, 76, 80]])

In [29]:
student_score > 80

array([[False,  True, False],
       [ True,  True,  True],
       [ True, False,  True],
       [False, False, False]])

In [30]:
student_score[student_score > 80]

array([88, 89, 90, 92, 83, 85])

In [31]:
student_score[[True, False, True, False], :2]

array([[79, 88],
       [83, 78]])

## 【任务2-3】评选优秀员工

In [32]:
import numpy as np

# 创建数组，用于保存所有员工的工作表现
employee_performance = np.array([[85, 90, 92], [78, 82, 80], 
                                 [88, 91, 89], [70, 75, 80]])



# 构建包含多个条件的布尔索引
performance_condition = (employee_performance[:, 0] > 80) & (employee_performance[:, 1] > 85)

# 使用布尔索引筛选符合要求的数据
filtered_performance = employee_performance[performance_condition]
filtered_performance

# 输出员工的姓名
employee_names = np.array(['Alice', 'Bob', 'Charlie', 'David'])
filtered_names = employee_names[performance_condition]
filtered_names



array(['Alice', 'Charlie'], dtype='<U7')

## 形状相同的数组间的算术运算

In [33]:
import numpy as np
arr_one = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr_two = np.array([[2, 3, 4, 5], [6, 7, 8, 9], [10, 11, 12, 13]])
arr_one + arr_two                # 两个数组进行加法运算

array([[ 3,  5,  7,  9],
       [11, 13, 15, 17],
       [19, 21, 23, 25]])

In [34]:
arr_one - arr_two                # 两个数组进行减法运算

array([[-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

In [35]:
arr_one * arr_two                # 两个数组进行乘法运算

array([[  2,   6,  12,  20],
       [ 30,  42,  56,  72],
       [ 90, 110, 132, 156]])

In [36]:
arr_one / arr_two                # 两个数组进行除法运算

array([[0.5       , 0.66666667, 0.75      , 0.8       ],
       [0.83333333, 0.85714286, 0.875     , 0.88888889],
       [0.9       , 0.90909091, 0.91666667, 0.92307692]])

## 形状不同的数组间的算术运算

In [37]:
import numpy as np
arr_one = np.array([[1], [5], [9]])
arr_one.shape

(3, 1)

In [38]:
arr_two = np.array([1, 2, 3, 4])
arr_two.shape

(4,)

In [39]:
arr_res = arr_one + arr_two
arr_res.shape

(3, 4)

In [40]:
arr_res

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

## 数组与标量的算术运算

In [41]:
import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
value = 10
arr_2d + value        # 数组与标量相加

array([[11, 12, 13],
       [14, 15, 16]])

In [42]:
arr_2d - value        # 数组与标量相减

array([[-9, -8, -7],
       [-6, -5, -4]])

In [43]:
arr_2d * value        # 数组与标量相乘

array([[10, 20, 30],
       [40, 50, 60]])

In [44]:
arr_2d / value         # 数组与标量相除

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6]])

## 数组的统计运算

In [45]:
import numpy as np
arr = np.arange(10)
arr.sum()      # 求和

np.int64(45)

In [46]:
arr.mean()     # 求平均值

np.float64(4.5)

In [47]:
arr.min()      # 求最小值

np.int64(0)

In [48]:
arr.max()       # 求最大值

np.int64(9)

In [49]:
arr.argmin()   # 求最小值的索引

np.int64(0)

In [50]:
arr.argmax()   # 求最大值的索引

np.int64(9)

In [51]:
arr.cumsum()   # 计算元素的累计和

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [52]:
arr.cumprod()  # 计算元素的累计积

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## 【任务2-4】计算同比增速

In [53]:
import numpy as np

last_year_data = np.array([
    [100, 105, 111],
    [115, 113, 120],
    [130, 125, 131],
    [150, 151, 160]])

this_year_data = np.array([
    [110, 125, 135],
    [145, 155, 165],
    [175, 185, 195],
    [205, 215, 225]])

In [54]:
# 计算每个月的同比增速（百分比）
growth_rate = (this_year_data - last_year_data) / last_year_data * 100
growth_rate


array([[10.        , 19.04761905, 21.62162162],
       [26.08695652, 37.16814159, 37.5       ],
       [34.61538462, 48.        , 48.85496183],
       [36.66666667, 42.38410596, 40.625     ]])

In [55]:
# 计算全年的平均增速（百分比）
average_growth_rate = growth_rate.mean()
average_growth_rate



np.float64(33.547538154856454)

In [56]:
# 计算全年的最高增速（百分比）
max_growth_rate = growth_rate.max()
max_growth_rate



np.float64(48.854961832061065)

In [57]:
# 计算全年的最低增速（百分比）
min_growth_rate = growth_rate.min()
min_growth_rate



np.float64(10.0)

## 随机数模块

In [58]:
import numpy as np
np.random.rand(3, 3)     # 随机生成一个二维数组

array([[0.20965412, 0.80547272, 0.02400919],
       [0.09508737, 0.88427034, 0.27354828],
       [0.9970957 , 0.18879689, 0.82703004]])

In [59]:
np.random.rand(2, 3, 3) # 随机生成一个三维数组

array([[[0.71853222, 0.86612868, 0.75983744],
        [0.3231992 , 0.00304855, 0.5404849 ],
        [0.53609873, 0.20342086, 0.26920215]],

       [[0.6964023 , 0.06352542, 0.18094789],
        [0.91128207, 0.354965  , 0.9567894 ],
        [0.70734108, 0.02386441, 0.21744959]]])

In [60]:
import numpy as np
np.random.seed(0)   # 生成随机数的种子
np.random.rand(5)   # 随机生成包含5个元素的浮点数组

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [61]:
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [62]:
np.random.seed()
np.random.rand(5)

array([0.79177964, 0.4536802 , 0.42618388, 0.17987049, 0.80592279])

## 数组的通用函数

In [63]:
import numpy as np
arr_int = np.array([1, -5, 8, -10])
arr_float = np.array([1.3, -5.5, 8.0, -10.7])
arr_bool = np.array([np.nan, np.nan, 8.0, -10.7])
np.fabs(arr_int)     # 计算数组中各元素的绝对值，每个绝对值都是浮点数

array([ 1.,  5.,  8., 10.])

In [64]:
np.square(arr_int)  # 计算数组中各元素的平方

array([  1,  25,  64, 100])

In [65]:
np.ceil(arr_float)   # 计算数组中各元素的ceilling值

array([  2.,  -5.,   8., -10.])

In [66]:
np.floor(arr_float)   # 计算数组中各元素的floor值

array([  1.,  -6.,   8., -11.])

In [67]:
np.rint(arr_float)   # 计算数组中各元素四舍五入的值

array([  1.,  -6.,   8., -11.])

In [68]:
np.modf(arr_float)   # 返回数组中各元素的小数部分和整数部分

(array([ 0.3, -0.5,  0. , -0.7]), array([  1.,  -5.,   8., -10.]))

In [69]:
np.isnan(arr_bool)   # 判断数组中各元素的值是否为NaN

array([ True,  True, False, False])

In [70]:
import numpy as np
arr_one = np.array([1, 5, 10, 4])
arr_two = np.array([6, 2, 8, 9])
# 计算数组arr_one和arr_two中各元素相加的结果
np.add(arr_one, arr_two)     

array([ 7,  7, 18, 13])

In [71]:
# 计算数组arr_one和arr_two中各元素的最大值
np.maximum(arr_one, arr_two)

array([ 6,  5, 10,  9])

In [72]:
# 计算数组arr_one和arr_two中各元素求模的结果
np.mod(arr_one, arr_two)  

array([1, 1, 2, 4])

In [73]:
# 比较数组arr_one是否小于或等于arr_two
np.less_equal(arr_one, arr_two) 

array([ True, False, False,  True])

## 条件逻辑

In [74]:
import numpy as np
arr_x = np.array([1, 5, 7])
arr_y = np.array([2, 6, 8])
arr_con = np.array([True, False, True])

In [75]:
result = np.where(arr_con, arr_x, arr_y)
result

array([1, 6, 7])

## 【任务2-5】随机漫步

In [76]:
import numpy as np

# 随机产生的步数情况
steps = 2000
draws = np.random.randint(0, 2, size=steps)
# 当draws的元素为1时，direction_steps的元素为1，
# 当draws的元素为0时，direction_steps的元素为-1
direction_steps = np.where(draws > 0, 1, -1)
direction_steps

array([-1, -1, -1, ...,  1,  1, -1], shape=(2000,))

In [77]:
# 计算步数累计和 （提示：cumsum()函数)
cumulative_steps = direction_steps.cumsum()
cumulative_steps



array([-1, -2, -3, ..., -2, -1, -2], shape=(2000,))

In [78]:
# 计算向前走的最远距离
max_forward_distance = cumulative_steps.max()
max_forward_distance


np.int64(38)

In [79]:
# 计算向后走的最远距离
max_backward_distance = cumulative_steps.min()
max_backward_distance



np.int64(-38)

In [80]:
# 将 15 米换算成步数
meters_per_step = 0.8
steps_per_meter = 1 / meters_per_step
steps_for_15_meters = 15 * steps_per_meter
steps_for_15_meters



18.75

## 数组的重塑

In [81]:
import numpy as np
array_1d = np.arange(1, 13)
print('原数组的形状：' + str(array_1d.shape))
print(array_1d)
array_2d = array_1d.reshape((6,2))
print('新数组的形状：' + str(array_2d.shape))
print(array_2d)

原数组的形状：(12,)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
新数组的形状：(6, 2)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [82]:
new_array_2d = array_2d.reshape((3,4))
print('新数组的形状：' + str(new_array_2d.shape))
print(new_array_2d)

新数组的形状：(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 数组的转置

In [83]:
import numpy as np
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
arr.T      # 使用T属性对数组进行转置

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

## 数组的垂直堆叠

In [85]:
import numpy as np
# 创建两个数组
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
# 沿着垂直方向堆叠两个数组
stacked_arr = np.vstack((arr1, arr2))
print("堆叠后的数组：")
print(stacked_arr)

堆叠后的数组：
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## 【任务2-6】转换销售数据

In [86]:
import numpy as np

# 创建一维数组，代表转换前的销售数据
sales_data = np.array([100, 150, 200, 250, 300, 350])

# 重塑一维数组
sales_data_2d = sales_data.reshape((2, 3))
print("重塑后的二维数组：")
print(sales_data_2d)

# 转置二维数组
sales_data_2d_transposed = sales_data_2d.T
print("转置后的二维数组：")
print(sales_data_2d_transposed)

# 计算每一列的总和
column_sums = sales_data_2d_transposed.sum(axis=0)
print("每一列的总和：")
print(column_sums)

# 将总和添加到二维数组的最后一行
sales_data_2d_with_sums = np.vstack
((sales_data_2d_transposed, column_sums))
print("添加总和后的二维数组：")
print(sales_data_2d_with_sums)



重塑后的二维数组：
[[100 150 200]
 [250 300 350]]
转置后的二维数组：
[[100 250]
 [150 300]
 [200 350]]
每一列的总和：
[450 900]
添加总和后的二维数组：
<function vstack at 0x0000029B4F9042C0>


## 数组的排序

In [87]:
import numpy as np
arr = np.array([[6, 2, 7], [3, 6, 2], [4, 3, 2]])
arr

array([[6, 2, 7],
       [3, 6, 2],
       [4, 3, 2]])

In [88]:
arr.sort()
arr

array([[2, 6, 7],
       [2, 3, 6],
       [2, 3, 4]])

In [89]:
arr = np.array([[6, 2, 7], [3, 6, 2], [4, 3, 2]])
arr

array([[6, 2, 7],
       [3, 6, 2],
       [4, 3, 2]])

In [90]:
arr.sort(0)       # 沿着编号为0的轴对元素排序
arr

array([[3, 2, 2],
       [4, 3, 2],
       [6, 6, 7]])

## 检索数组元素

In [91]:
import numpy as np
arr = np.array([[1, -2, -7], [-3, 6, 2], [-4, 3, 2]])
arr

array([[ 1, -2, -7],
       [-3,  6,  2],
       [-4,  3,  2]])

In [92]:
np.any(arr > 0)      # 检索arr的所有元素是否有一个大于0

np.True_

In [93]:
np.all(arr > 0)      # 检索arr的所有元素是否都大于0

np.False_

## 【任务2-7】分店销售信息汇总

In [94]:
import numpy as np

# 每个门店销售量
sales_data = np.array([
    [550, 700, 620, 800],   # 门店1
    [430, 500, 480, 550],   # 门店2
    [900, 850, 950, 1000],  # 门店3
    [720, 680, 710, 690],   # 门店4
    [620, 580, 600, 650],   # 门店5
    [800, 750, 780, 820]    # 门店6
])

sales_data

array([[ 550,  700,  620,  800],
       [ 430,  500,  480,  550],
       [ 900,  850,  950, 1000],
       [ 720,  680,  710,  690],
       [ 620,  580,  600,  650],
       [ 800,  750,  780,  820]])

In [95]:
# 计算每个门店最多的销售量
max_sales_per_store = sales_data.max(axis=1)
print("每个门店最多的销售量：")
print(max_sales_per_store)



每个门店最多的销售量：
[ 800  550 1000  720  650  820]


In [96]:
# 计算每个门店的总销售量
total_sales_per_store = sales_data.sum(axis=1)
print("每个门店的总销售量：")
print(total_sales_per_store)

每个门店的总销售量：
[2670 1960 3700 2800 2450 3150]


In [97]:
# 检查每个商品的销售量是否都在合理的范围内
reasonable_sales = (sales_data >= 400) & (sales_data <= 1000)
print("每个商品的销售量是否都在合理的范围内：")
print(reasonable_sales)


每个商品的销售量是否都在合理的范围内：
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


## 查找数组的唯一元素

In [98]:
import numpy as np
arr = np.array([12, 11, 34, 23, 12, 8, 11])
np.unique(arr)

array([ 8, 11, 12, 23, 34])

In [99]:
import numpy as np
arr = np.array([12, 11, 34, 23, 12, 8, 11])
np.unique(arr, return_index=True)

(array([ 8, 11, 12, 23, 34]), array([5, 1, 0, 3, 2]))

## 数组的展开

In [100]:
import numpy as np
# 创建一个二维数组
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
# 将二维数组转换为一维数组
flattened_arr = arr.flatten()
flattened_arr

array([1, 2, 3, 4, 5, 6])

## 【任务2-8】兴趣班调查

In [102]:
import numpy as np

# 兴趣班信息
course_data = np.array([
    ["张三", "舞蹈", "钢琴", "武术"],
    ["李四", "绘画", "舞蹈", "游泳"],
    ["王五", "游泳", "舞蹈", "轮滑"],
    ["赵六", "轮滑", "绘画", "武术"],
    ["周七", "外语", "声乐", "绘画"],
    ["韩八", "游泳", "外语", "钢琴"],
    ["秦九", "篮球", "钢琴", "声乐"],
    ["郑十", "轮滑", "篮球", "绘画"]
])

course_data

array([['张三', '舞蹈', '钢琴', '武术'],
       ['李四', '绘画', '舞蹈', '游泳'],
       ['王五', '游泳', '舞蹈', '轮滑'],
       ['赵六', '轮滑', '绘画', '武术'],
       ['周七', '外语', '声乐', '绘画'],
       ['韩八', '游泳', '外语', '钢琴'],
       ['秦九', '篮球', '钢琴', '声乐'],
       ['郑十', '轮滑', '篮球', '绘画']], dtype='<U2')

In [103]:
# 提取所有兴趣班（提示：np.flatten
all_courses = course_data[:, 1:].flatten()
print("所有兴趣班：")
print(all_courses)

# 统计各兴趣班的人数（提示：np.unique(x, return_counts=True)
unique_courses, counts = np.unique(all_courses, return_counts=True)
print("兴趣班及其人数：")
for course, count in zip(unique_courses, counts):
    print(f"{course}: {count}人")


所有兴趣班：
['舞蹈' '钢琴' '武术' '绘画' '舞蹈' '游泳' '游泳' '舞蹈' '轮滑' '轮滑' '绘画' '武术' '外语' '声乐'
 '绘画' '游泳' '外语' '钢琴' '篮球' '钢琴' '声乐' '轮滑' '篮球' '绘画']
兴趣班及其人数：
声乐: 2人
外语: 2人
武术: 2人
游泳: 3人
篮球: 2人
绘画: 4人
舞蹈: 3人
轮滑: 3人
钢琴: 3人
